Fix `dead_code` warnings on non-`x86_64` targets
Rustc probably has a regression bug.

`dead_code` warnings are not emitted on arch loongarch64 and riscv64;
instead, if `#[expect(dead_code)]` is set, we got:

error: this lint expectation is unfulfilled
  --> kernel/src/syscall/clock_gettime.rs:69:14
   |
69 |     #[expect(dead_code)]
   |              ^^^^^^^^^
   |
   = note: `-D unfulfilled-lint-expectations` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(unfulfilled_lint_expectations)]`

[Error]: Command RUSTFLAGS="-Dwarnings --check-cfg cfg(ktest)" "cargo"
"clippy" "-Zbuild-std=core,alloc,compiler_builtins"
"-Zbuild-std-features=compiler-bui ltins-mem" "--target"
"riscv64imac-unknown-none-elf" "--no-deps" failed with status:
ExitStatus(unix_wait_status(25856))

These code are really not read, but to pass lint check, we only set
`#[expect(dead_code)]` on x86_64 target.